apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-frontend
  labels:
    app: simple-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
    spec:
      containers:
      - name: simple-frontend
        image: ${{ secrets.DOCKER_USERNAME }}/simple-frontend:${{ matrix.node-version }}
        ports:
        - containerPort: 80