apiVersion: v1
kind: Service
metadata:
  name: simple-frontend

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: simple-frontend